#!/usr/bin/env bash

set -e

TIMES=3
FILE=prayerbook.tex
BOOKLET_FILE=booklet.tex

pushd "tex/"

(I=0
while [ $TIMES -gt $I ]; do
    lualatex -output-directory ../pdf/ $FILE
    ((++I))
done

lualatex -output-directory ../pdf/ $BOOKLET_FILE) 

popd
